[package]
name = "nyx-network"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nyx-common = { path = "../nyx-common" }
nyx-crypto = { path = "../nyx-crypto" }
nyx-protocol = { path = "../nyx-protocol" }
tokio = { workspace = true }
tokio-socks = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
