[package]
name = "nyx-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
nyx-protocol = { path = "../nyx-protocol" }

[[bin]]
name = "fuzz_frame_parse"
path = "fuzz_targets/fuzz_frame_parse.rs"
test = false
doc = false
