[package]
name = "nyx-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nyx-common = { path = "../nyx-common" }
nyx-crypto = { path = "../nyx-crypto" }
nyx-protocol = { path = "../nyx-protocol" }
nyx-storage = { path = "../nyx-storage" }
thiserror = { workspace = true }
zeroize = { workspace = true , features = ["derive"]}
hex = "0.4"
serde = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
